;;; Sierra Script
;;; Talkers.sh -- Produced by SCI Companion
;;; This file should only be edited with the SCI Companion message editor

;;; 

(define NARRATOR 99)
(define PRINTMSG 97)
(define SYSMSG 98)
(define NOBODY 1)
(define HIPPIE 2)
(define LAWYER 3)
(define CLETUS 4)
(define BILL 5)
(define BAGI 6)
(define BELLA 7)
(define LARRY 8)
(define MONK 9)
(define KASPAR 10)
(define BARNARD 11)
(define RICHARD 12)
(define WOLFGANG 13)
(define BIG_JURG 14)
(define LIL_JURG 15)
(define BRAUGGI 16)
(define MERV 17)
(define HILDE 18)
(define BONEHEAD 19)
(define BRUNO 20)
(define CLIVE 21)
(define BIG_JIM 22)
(define ROGUE 23)
(define HEALER 24)
(define CAVEMAN 25)
(define MOBSTER 26)
(define BARTENDER 27)
(define DRYAD 28)
(define MEEP 29)
(define WITCH_MAMA 30)
(define GHOST 31)
(define GARGOYLE 32)
(define RED_STRIPPER 33)
(define WHITE_STRIPPER 34)
(define BUTCH 35)
(define CASSIDY 36)
(define ELSA 37)
(define GUARD 38)
(define VIKING 39)
(define PIRATE 40)
(define LINDA 41)
(define GIANT 42)
(define BOAT 43)
(define SAM 44)
(define ZARA 45)
(define REUNION_GUY 46)
(define ARMORED_GUY 47)
(define FAIRY_GREEN 48)
(define FAIRY_BLUE 49)
(define FAIRY_RED 50)
(define FAIRY_YELLOW 51)
(define BAKER 52)
(define WEAPON_MASTER 53)
(define SLINK 54)
(define BANKER 55)

